
# Gradient & Edge Operation

- Check [Toturial on Sobel Derivatives](https://docs.opencv.org/3.4.3/d2/d2c/tutorial_sobel_derivatives.html)

- Linear operators can be exchanged:

- The gradient of $G(\sigma)$ is approximated in discrete space: Sobel, Prewit, etc.


- Edge magnitude:

  - [Norm (mathematics)](https://en.wikipedia.org/wiki/Norm_(mathematics))
  - [L0 Norm, L1 Norm, L-Infinity Norm](https://medium.com/@montjoile/l0-norm-l1-norm-l2-norm-l-infinity-norm-7a7d18a4f40c)
  
1. Sobel X, Y
1. Sobel Magnitude & Direction
1. Canny Edge Detector

## Sobel-X

```{python sobelX, code=readLines('python/sobel-x.py')}
```

Q. Produce edge-enhanced image using a combination of binarization and sobel edge map.

## Canny Edge Detector

- Edge map is extracted. That is, the output contains 0/1 values only (1 for edge pixels).
- The result depends on the value of `sigma` ($\sigma$) that controls the width of Gaussian operator for edge detection.

```{python canny, code=readLines('python/canny-edge.py')}
```

1. Q. Try various values of `sigma`.
1. Q. Apply morphological operators to the edge map.
1. Q. Try to extract edge's connect data with `cv.findContours()`.

