



## With Pytorch NN Module

Let's see how to use Pytorch NN module. This is necessary to build up more complex neural network models.


```{python}
import torch
import matplotlib.pyplot as plt

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Use the nn package to define our model as a sequence of layers. nn.Sequential
# is a Module which contains other Modules, and applies them in sequence to
# produce its output. Each Linear Module computes output from input using a
# linear function, and holds internal Tensors for its weight and bias.
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)

# The nn package also contains definitions of popular loss functions; in this
# case we will use Mean Squared Error (MSE) as our loss function.
loss_fn = torch.nn.MSELoss(reduction='sum')

learning_rate = 1e-4
epochs = 300
res = []
for t in range(epochs):
    # Forward pass: compute predicted y by passing x to the model. Module objects
    # override the __call__ operator so you can call them like functions. When
    # doing so you pass a Tensor of input data to the Module and it produces
    # a Tensor of output data.
    y_pred = model(x)

    # Compute and print loss. We pass Tensors containing the predicted and true
    # values of y, and the loss function returns a Tensor containing the
    # loss.
    loss = loss_fn(y_pred, y)
    #print(t, loss.item())
    res.append (loss.item())

    # Zero the gradients before running the backward pass.
    model.zero_grad()

    # Backward pass: compute gradient of the loss with respect to all the learnable
    # parameters of the model. Internally, the parameters of each Module are stored
    # in Tensors with requires_grad=True, so this call will compute gradients for
    # all learnable parameters in the model.
    loss.backward()

    # Update the weights using gradient descent. Each parameter is a Tensor, so
    # we can access its gradients like we did before.
    with torch.no_grad():
        for param in model.parameters():
            param -= learning_rate * param.grad
    #
#
print ('loss = {} after epochs {}'.format(loss, epochs))
fig, ax = plt.subplots();
ax.plot (range(1,1+epochs), res, '-')
fig.suptitle ('loss-epoch curve with NN module')
plt.show()
```

Previously, the network model is built by
```
y_pred = x.mm(w1).clamp(min=0).mm(w2)
```
Now we build it with the help of `torch.nn.Sequential`:
```
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
```
From top to bottom, the input data flows, and the model does (1) linear matrix operation, (2) ReLU, and (3) another linear matrix operation. The size of the matrices are given in the definition. See the full detail in [torch.nn.Sequential](https://pytorch.org/docs/stable/nn.html#sequential), including additional methods to define models.


The `torch.nn` package also contains definitions of popular loss functions; in this
case we use Mean Squared Error (MSE) as our loss function. [torch.nn.MSELoss](https://pytorch.org/docs/stable/nn.html#mseloss).
```
loss_fn = torch.nn.MSELoss(reduction='sum')
```
Compare this to the previous defintion of the same loss function:
```
loss = (y_pred - y).pow(2).sum()
```

One good thing to use `torch.nn.Sequential` to make the model is that we can use the model as if it is a function that accepts `x` as input. Well, it is actually a function. In the learning loop, this makes the code look concise.
```
y_pred = model(x)
```
Likewise, `loss_fn` is also a function. We compute `loss` by providing `y_pred` and `y`:
```
loss = loss_fn(y_pred, y)
```

Gradient computation is done in the same way:
```
loss.backward()
```
However, we must clear the gradient buffer in `model`. Otherwise, the gradient values will be added up along the iteration.
```
model.zero_grad()
```

Now, it is time to apply gradient descent. We don't have the explicit definiton of the parameter variables which was `w1`, `w2`, but `model` has them defined inside.
```
  with torch.no_grad():
      for param in model.parameters():
          param -= learning_rate * param.grad
```
By calling `model.parameters()` we may iterate & update the parameters one by one.