

## With Custom `nn` Modules

Sometimes you will want to specify models that are more complex than a sequence of existing Modules; for these cases you can define your own Modules by subclassing `torch.nn.Module` and defining a `forward` which receives input Tensors and produces output Tensors using other modules or other autograd operations on Tensors.


```{python}
import torch

class myNNModel(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(myNNModel, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred
#

N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

# Construct our model by instantiating the class defined above
model = myNNModel(D_in, H, D_out)
#
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)
#
res = []
nepochs = 100
for t in range(nepochs):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    res.append(loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
```


When defining the class, we have a few rules that must be kept.

1. it is import to make the class a derived class of `torch.nn.Module`. This is done by specifying it as follows:
```
class myNNModel(torch.nn.Module):
```

2. call `super()` at the first line of `__init__()` function.
```
    def __init__(self, D_in, H, D_out):
        super(myNNModel, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)
```
In the constructor we instantiate two `nn.Linear` modules and assign them as
        member variables.
        
3. make `forwad()` function to return the prediction from the model class.
```
  def forward(self, x):
      h_relu = self.linear1(x).clamp(min=0)
      y_pred = self.linear2(h_relu)
      return y_pred
```
In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.


Now the learning result. It should be similar.
```{python}
import matplotlib.pyplot as plt
print ('loss = {} after epochs {}'.format(loss, nepochs))
fig, ax = plt.subplots();
ax.plot (range(1,1+nepochs), res, '-')
ax.set_xlabel ('epoch');
ax.set_ylabel('loss')
fig.suptitle ('loss-epoch curve with Custom NN Module')
plt.show()
```




## Conclusion

That's it. This chapter gave explanations on the code given in [Learning Pytorch with Examples](https://pytorch.org/tutorials/beginner/pytorch_with_examples.html).

Now we are ready to go further.

