--- 
title: "Deep Learning with Pytorch: Explained Tutorials"
author: "서용덕 Yongduek Seo yndk@sogang.ac.kr"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Pytorch practice and deep learning. There are many tutorials in pytorch.org. Explanations are attached to learn it."
---

<!-- this is for Mac -->
<!-- # ``` {r} -->
<!-- # knitr::opts_chunk$set(engine.path = list( -->
<!-- #   python='/usr/local/bin/python3' -->
<!-- # )) -->
<!-- # ``` -->

<!-- ``` {r} -->
<!-- knitr::opts_chunk$set(engine.path = list( -->
<!-- python = 'c:/Vip/AppData/Local/Programs/Python/Python37/python.exe' -->
<!-- )) -->
<!-- ``` -->


- MacOS: python 3.7 install `https://docs.python.org/3/using/mac.html`
- MacOS:`matplotlib` backend problem can be solved by 
    - Create a file `~/.matplotlib/matplotlibrc` there and add the following code: `backend: TkAgg`


# Prerequisites


Proclaim: 

- Almost all the `pytorch` codes are from the tutorials in [pytorch.org](pytorch.org). They don't belong to me.

- This document is prepared using `rmarkdown` in `Rstudio`: [R Markdown from RStudio](https://rmarkdown.rstudio.com/index.html)


I am hoping to consider following topics.

1. Install `pytorch`, `python 3.x`
1. `numpy` and `torch.Tensor`
1. Simple linear regression 
    - a line fitting for a data set of almost no noise: $y = w x + b$
    - random number generation for training and test
1. Simple two class classification
    - random number generation: uniform and Gaussian
    - feature and label - random data generation
    
1. Simple linear regression & classification with `DataLoader` & `DataSet`
    - Using `torch.nn` for the two simple problems: 
    - `class myNetwork(torch.nn)`
    - `optim` package
    
1. Sobel Operater Learning with Convolutional Neural Network
    - Single data example
    - Sobel ?
    - convoltuion ?
    - single channel (gray scale) and multi-channel (RGB)
    
1. MNIST image classification
    1. With Fully connected network
        - `numpy.ravel()`
    1. With Convolutional Neural Network

1. Dogs and Cats with Transfer Learning
    - ResNet, DensetNet, VggNet, etc
    - Transfer Learning: Use a trained network for classification of not-trained sources.
    
1. Dogs Breed Classification
    - Kaggle interface
    - Transfer Learning
  
1. Direct Font Style Transfer
    - Using `PIL` to draw characters on the image bitmap
    - `numpy` as image data container



Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.name/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

Python 언어를 사용하는 방법은 ... 쉽다.

```{python}
import sys
print (sys.version)
```


You can apply `OpenCV` image processing and show the results.
```{python, opencv}
import matplotlib.pyplot as plt
import numpy as np
import cv2
#
ii = cv2.imread('images/Unequalized_Hawkes_Bay_NZ.jpg', 0)
hist,bins = np.histogram (ii.flatten(), 256, [0,256])
cdf = hist.cumsum()
cdf_normalized = cdf * hist.max() / cdf.max()


equ = cv2.equalizeHist (ii)
fig, ax = plt.subplots(1,3)
ax[0].imshow(ii, cmap='gray')
ax[1].imshow(equ, cmap='gray')
ax[2].plot (cdf_normalized, color='b')
#ax[2].hist(ii.flatten(), 256, [0,256], color='r')
#ax[2].xlim([0,256])
```